### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by Dekablade01** [Sadmansamee/Survey#10]
- There're still many classes lack of testing, and some cases are not covered with unit tests
  - `TokenService`, `HomeViewModel` failure case, `AuthViewModel` failure case, etc …

**Comment by Dekablade01** [comment]
Also, I was curious about what does `sut` means in unit tests?

**Comment by Sadmansamee** [comment]
It most likely means "System Under Test", i.e. the system being tested, as opposed to other systems it may interact with, but which are not being explicitly tested (because they're someone else's responsibility).

**Comment by Sadmansamee** [comment]
#11

**Comment by Sadmansamee** [comment]
@Dekablade01
