### ISSUE TITLE
Coding Style

### ISSUE THREAD

**Issue by Dekablade01** [Sadmansamee/Survey#2]
- Why did you prefer `SwiftyJSON` over `Codable` ? 
- Why did you prefer `UserDefaults` over `Keychain` ? 
- Lots of code comments are remain in the project. 
- There should not be any function or variable on top of everything. 
![picture](https://i.imgur.com/TOqW98M.png)
- Naming variable is not describing what it is 
![picture](https://i.imgur.com/69D4zlv.png)

**Comment by Sadmansamee** [comment]
@Dekablade01  #6 This issue has been resolved into this pull request

**Comment by Sadmansamee** [comment]
@Dekablade01
